---
- name: Update and upgrade apt packages
  hosts: all
  become: true

  tasks:
    - name: Update packages with apt
      apt:
        update_cache: true

    - name: Upgrade packages with apt
      apt:
        upgrade: dist
        autoremove: true
        autoclean: true
